app_login:
    path: /login
    controller: App\Controller\LoginController::index
    condition: "not has_role('ROLE_USER')"
app_logout:
    path: /logout
    methods: GET
register:
    path: /register
    controller: App\Controller\RegisterController::index
home:
    path: /home
    controller: App\Controller\HomeController::index
    # role: ROLE_USER
tweet:
    path: /tweet
    controller: App\Controller\TweetController::index
    # role: ROLE_USER